### ISSUE TITLE
Zoomer does not affect Marker and Breakpoint layers

### ISSUE THREAD

**Issue by thomasfillon** [wavesjs/zoomer#2]
When zooming in a given Timeline, `marker` and `breakpoint` layers are not affected (`segment`, `label` and `waveform` layers are).

See
https://jsfiddle.net/thomasfillon/6jtxrsqh/

**Comment by b-ma** [comment]
There is actually something strange, segment, label and waveform shouldn't be updated...
The problem is fixed if you call `graph.update()` in the zoomer's `mousemove` event.

Your fixed example here : https://jsfiddle.net/6jtxrsqh/20/

**Comment by thomasfillon** [comment]
OK great ! Thank you Benjamin for the fix.

Regarding documentation: the example [here](http://ircam-rnd.github.io/waves/examples/01-ui-what-you-can-do-with-it.html) is fine
but [this one](http://ircam-rnd.github.io/waves/ui/#ui-zoomer-example-usage) need to be fixed with the `graph.update()`  call.

**Comment by b-ma** [comment]
fixed, thank you
